version: 2

models:
  - name: mta_staging
    description: Deduplicate, clean up timestamps and labels, prep for diff
    config:
      materialized: table
      tags: ['SQL']

  - name: mta_diff
    description: First-difference the turnstile counters, keeping 0 <= diff <= 7200
    config:
      materialized: table
      tags: ['SQL']

  - name: entry_avg
    description: Compute ENTRIES observation counts, means and SDs by turnstile for anomaly detection
    config:
      materialized: table
      tags: ['SQL']

  - name: exit_avg
    description: Compute EXITS observation counts, means and SDs and a cutoff by turnstile
    config:
      materialized: table
      tags: ['SQL']

  - name: mta_clean
    description: SQL Drop rows based on the computed cutoff (disabled), merge from station_map
    columns:
    - name: date
    - name: hour
    - name: station
      tests:
        - not_null
    - name: turnstile
    - name: entries
    - name: exits
    config:
      materialized: table
      tags: ['SQL']

  - name: station_list
    description: list of stations, lat/lon, etc
    config:
      materialized: table
      tags: ['SQL']

