version: 2

sources:
  - name: mta
    description: MTA raw turnstile data 
    tables:
    - name: mta_raw
      description: raw unmodified data ingested from downloads directory. see https://data.ny.gov/api/views/py8k-a8wg/files/5c602688-3031-4f39-8f2b-d4a3cd8c3752?download=true&filename=MTA_Turnstile_Data_DataDictionary.pdf
      columns:
      - name: C/A
      - name: UNIT
      - name: SCP
      - name: STATION
      - name: LINENAME
      - name: DIVISION
      - name: DATE
      - name: TIME
      - name: DESC
      - name: ENTRY_COUNTER
      - name: EXIT_COUNTER
models:
  - name: mta_staging
    description: SQL model to deduplicate, clean up timestamps and labels
    config:
      materialized: table
      tags: ['SQL']

  - name: mta_diff
    description: SQL model to first-difference the turnstile counters, keeping 0 <= diff <= 7200
    config:
      materialized: table
      tags: ['SQL']

  - name: entry_avg
    description: SQL model to compute ENTRIES observation counts, means and SDs by turnstile
    config:
      materialized: table
      tags: ['SQL']

  - name: exit_avg
    description: SQL model to compute EXITS observation counts, means and SDs and a cutoff by turnstile
    config:
      materialized: table
      tags: ['SQL']

  - name: mta_clean
    description: SQL model to drop rows based on the computed cutoff
    config:
      materialized: table
      tags: ['SQL']
