version: 2

seeds:
  - name: division_label_override
    description: Suffix to append to stations based on division, e.g. PATH, SIR 
    columns:
      - name: division_src
        tests:
          - unique
          - not_null
      - name: division_dest
        tests:
          - not_null
  - name: station_label_override
    description: Station label overrides to merge stations with more than 1 name 
    columns:
      - name: station_src
        tests:
          - unique
          - not_null
      - name: station_dest
        tests:
          - not_null
  - name: station_map
    description: additional station data not in turnstile files, longitude, latitude, cbd, pretty name
    columns:
      - name: Station
      - name: Complex
      - name: Stop_ID
      - name: Division
      - name: Line
      - name: Stop_Name
      - name: Borough
      - name: Daytime_Routes
      - name: Structure
      - name: Latitude
      - name: Longitude
      - name: North_Label
      - name: South_Label
      - name: CBD
